### ISSUE TITLE
Are there any possible ways to package the app to a normal macOS application ?  

### ISSUE THREAD

**Issue by bitflying** [murlokswarm/app#179] opened 2018-08-27 03:51 UTC
Hi, friends,

Are there any possible ways to package the app to a normal macOS application ?  

Thanks in advance!

**Comment by maxence-charriere** [comment] 2018-08-27 04:35
Yes, take a look on the issue bellow :)
https://github.com/murlokswarm/app/issues/175

**Comment by maxence-charriere** [comment] 2018-08-27 04:39
Duplicate of #175

**Closed by maxence-charriere** 2018-08-27 04:39 UTC

**Comment by maxence-charriere** [comment] 2018-08-27 04:47
Also created a wiki page that contains the answer of the duplicate.
https://github.com/murlokswarm/app/wiki/Package-MacOS-app

Please reopen the issue and add suggestions if you think this is too light.
Best.

**Comment by bitflying** [comment] 2018-08-27 05:05
Thanks, Maxence Charriere,

It is great!
